### ISSUE TITLE
Android 수동 설치 시 에러 발생

### ISSUE THREAD

**Issue by jasonkang14** [shpongle2634/react-native-kakao-plus-friend#2]
Android 수동 설치를 위해
`android/app/src/main/java/[...]/MainActivity.java` 에
`import com.reactlibrary.RNKakaoPlusFriendPackage;` 라인을 추가하면

아래와 같은 에러가 발생합니다.

`error: package com.reactlibrary does not exist`

`reactlibrary`라는 것을 추가로 설치해야 하는건가요?

**Comment by shpongle2634** [comment]
안녕하세요,

복붙을 하다보니.. 패키지명이 문서에 반영이 안된 것 같습니다ㅠ

RNKakaoPlusFriendPackage는 com.jootopia.kakao.plus에 있습니다.

import com.jootopia.kakao.plus.RNKakaoPlusFriendPackage;로 변경부탁드립니다.

**Comment by jasonkang14** [comment]
말씀하신대로 하니 이번에는
`error: package com.jootopia.kakao.plus does not exist`라는 에러가 나옵니다. 

사실 그동안 잘 작동되던것이 왜 에러가 나는지는 잘 모르겠습니다만...
수정하거나 추가해야하는 부분이 있을까요?

**Comment by jasonkang14** [comment]
혹시 해당 라인을 `MainActivity.java`가 아니라 `MainApplication.java`에 추가해야하는 건가요?

**Comment by jasonkang14** [comment]
지속적인 질문 죄송합니다... library source code를 찾아보니 실제로는 `co.jootopia.kakao.plus`인 듯 하네요

**Comment by shpongle2634** [comment]
앗 com으로 오기가 있었군요 ㅠ 죄송합니다
다른 질문 있으시다면 언제든 알려주세요!
